### PR TITLE
Scaled-down versions of images in "travel.html";  simplify classes in and CSS selectors for "favorite.html".

### PR DESCRIPTION
**Pull request by mfreema5**
There seem to be a lot of places where I removed a line, then added exactly the same line back in.  I think that's TextWrangler automatically stripping the trailing whitespace off of lines.  It makes it a little harder to find the actual changes.  Sorry.

---

Anyway, the free, open-source software package ImageMagick contains the command-line tool `convert`, which is useful for scaling images in batches.  I created scaled versions of the large images in the repo.  E.g., file `FOO.JPG` was scaled to create `FOO__scale256.jpg` and `FOO__scale960.jpg`, which are 260px and 960px wide, respectively.

I'm not sure what you were going for with the image arrangement on the “`travel.html`” page.  When I first opened that page the images showed up three across in a row.  But since you used `<li></li>` elements, I'm assuming you want them in a vertical stack, and so I fiddled things based on that assumption.  And I've changed the page to load the 960px-scaled versions of images.  (Loads a _lot_ faster since, e.g., `Sudan/P3080064` went from being a 1,638K file to a 116K file.  For really small screens, you might want to use the 256px-scale images, since, with the same example, it would only have to load a 29K file… about 2% of the weight of the original.)

Apparently, you can size images in CSS using `em` units, so I've done that.  Just be aware that the size of an `em` cascades from block-container elements to contained elements.  (Which is a never-ending source of bafflement for me while designing pages.)  So, if the containing block has the font-size set to 225%, the default 16px `em` is now a 36px `em`, and an 18em-sized image in a child element is 648px wide, not 288px.  And, as far as I know, you need only set the width or height, and the other dimension is set based on of the proportions of the original image.  By using `em` units, I could drop the image-size style from one level of the media-queries.  You might-could remove one or two more.

Along the way, I reduced the specificity of some selectors in the CSS related to the “`travel.html`” page.  It didn't seem like they were fighting with any others for precedence, and the long combinations of selector elements confused me.

---

The classes “`favorite-books`”, “`favorite-melodies`”, and “`favorite-movies`” were never styled differently from each other.  And the elements they are applied to are all under an element of class “`favorite`”.  So I removed them.  We can use that “`favorite`” class alone to select the elements we want to style, and drop any selectors that aren't completely necessary.  So that: 

``` CSS
ul.favorite-books li ul li, ul.favorite-melodies li ul li, ul.favorite-movies li ul li»
```

Becomes: 

``` CSS
.favorite ul ul li
```

Even better, we can shrink: 

``` CSS
ul.favorite-books li ul li img, ul.favorite-melodies li ul li img, ul.favorite-movies li ul li img
```

Into: 

``` CSS
.favorite img
```

(That all works as far as I can tell; you should probably double-check.)

Oh, and to help myself figure all that out, I had to re-indent the file “`favorite.html`”.  The only substantive changes I made were to remove the unused classes.  Other than that all I did was add a bunch of line-breaks, and add&remove a bunch of spaces.  (Obsessively indented HTML has a certain sinusoidal beauty, don't'cha think?)

---

From the opening page of the PDF of _Making a World of Difference_:

> Copyright 2011… no part of this publication may be reproduced, distributed or transmitted in any form or by any means, or stored in database or retrieval system without the prior written permission of the copyright holder.

I deleted it from this very openly-accessible online repository.

---

Finally, in “screen.css” there was a line in “`html{}`” that was throwing an error, because it refers to a non-existant URL:

``` CSS
background-image: url("../Background/.jpg");
```

I commented it out, so that there are no errors in the console when you view the pages.  I didn't delete it because I don't know if that's just a typo or not.

### CODE REVIEW

**Comment by mfreema5** [comment]
It occurred to me that you probably did want the images on the “travel” page to line up laterally.  So, I've made some additional changes to make that happen.

I've added inline comments in “screen.css” for most of the changes I made there.

In the HTML, I've removed the `<li></li>` elements from around the images.  You don't really need them.  I've added anchors/links to the original-sized images, and coded the HTML to diplay images scaled to 512px wide. I wrapped the “view more” link in `<p></p>` elements to have something to apply styles to.  (I guess I could have left that one set of `<li></li>`, but they were the last set in the nested `<ul>`.  By removing them, I could remove the entire nested list.)  While I was at it, I also made the “view more” link “`text-align: right`”, since presumably readers will scan across the images from left to right.

Of course, what occurs to me now is that layering yet another commit on top of the commit which I already requested you pull into your master branch is just going to quadruple the confusion for you.  Sorry.  I wasn't trying to baffle you.  I just got intrigued by how to get the images to line up nicely, and next thing you know….

You can always just close this pull request and pretend it never happened.

Mike

**Comment by xbim1810** [comment]
Thank you. Mike. I really appreciate your comment and I'll check the revision as soon as possible. Hope I can give some useful ideas as to your project later.Thank you very much! Have a good weekend and a good Thanksgiving holiday! Best,Bing------------------------------------------------------------------发件人：M.J. Freeman notifications@github.com发送时间：2014年11月22日(星期六) 11:19收件人：xbim1810/xbim1810.github.io xbim1810.github.io@noreply.github.com主　题：Re: [xbim1810.github.io] Scaled-down versions of images in "travel.html";  simplify classes in and CSS selectors for "favorite.html". (#1)
It occurred to me that you probably did want the images on the “travel” page to line up laterally.  So, I've made some additional changes to make that happen.

I've added inline comments in “screen.css” for most of the changes I made there.

In the HTML, I've removed the <li></li> elements from around the images.  You don't really need them.  I've added anchors/links to the original-sized images, and coded the HTML to diplay images scaled to 512px wide. I wrapped the “view more” link in <p></p> elements to have something to apply styles to.  (I guess I could have left that one set of <li></li>, but they were the last set in the nested <ul>.  By removing them, I could remove the entire nested list.)  While I was at it, I also made the “view more” link “text-align: right”, since presumably readers will scan across the images from left to right.

Of course, what occurs to me now is that layering yet another commit on top of the commit which I already requested you pull into your master branch is just going to quadruple the confusion for you.  Sorry.  I wasn't trying to baffle you.  I just got intrigued by how to get the images to line up nicely, and next thing you know….

You can always just close this pull request and pretend it never happened.

Mike

**Comment by xbim1810** [comment]
HI, Mike,

Thank you for your improvements in my webpage. The layout looks more orderly and organized after you revised on it. You are right in the "class" issue in the page favorite.html. I do not have to use so many "class" tags. And in my css the background-image is invalid and I forgot to delete the line.

In the page travel.html, yes, I planned to display the images inline so the space can be fully employed and it will provide more information to the audience without scrolling too much.  I also agree that I need not use ul and li for all content I added. I added them because last time without them the html could not pass the check of validator. However, after your improvement, it still past the check. That is what result I hope to get. Thank you for this effort. 

But I do not think that so many archors/links display in the page is better than images. You can check the page by yourself. For "view more", I think people will view the whole page first to learn what is on the page before checking them line by line. So I think it can be kept at their position to get more chance to be viewed by the audience.  We can discuss it later. 

Best,
Bing

**Comment by mfreema5** [comment]
> But I do not think that so many archors/links display in the page is better than images.

I'm not sure I understand what you are saying.  The images are still being displayed on the page.  The page is just loading a smaller (in px and in KB) version.  The anchors are there to make it possible to click on a picture and see the full-sized version of it.

bing-travel

I'll leave the test version in place on my Macbook, you can look at it in class, if you want.

**Comment by xbim1810** [comment]
Sorry for this point, in my computer they cannot display but only "alt" in it. 
Thanks for your explanation. I'll check again.

**Comment by mfreema5** [comment]
You might also be able to see my version rendered at: [http://htmlpreview.github.io/?https://raw.githubusercontent.com/mfreema5/xbim1810.github.io/master/travel/travel.html](http://htmlpreview.github.io/?https://raw.githubusercontent.com/mfreema5/xbim1810.github.io/master/travel/travel.html).  (Sometimes that hackity preview thingy works; sometimes it doesn't.)

**Comment by mfreema5** [comment]
I recommend that you install: [Image Magick for Windows](http://www.imagemagick.org/script/binary-releases.php#windows)

You'll be using the command [`convert`](http://www.imagemagick.org/script/convert.php).

There are some official usage examples here: [www.imagemagick.org/Usage/resize](http://www.imagemagick.org/Usage/resize/).  That page is an _excellent_ example of how to take a seemingly simple subject and make it completely inscrutable, by complicating the issue with technical details that 90% of readers would never care about.

So, here are some simplified examples, for creating a smaller version of the following image, `6.jpg`:

- If you want to create a copy of an image that's a specific size in pixels…
  - Copy to exactly 200px wide by 150px high (proportions be damned!)
    - `convert 6.jpg -scale 200x150\! 6_200x150.jpg`
      - 6_200x150
  - Copy to 200px wide, maintain original proportions
    - `convert 6.jpg -scale 200x 6_200x.jpg`
      - 6_200x
  - Copy to 150px high, maintain original proportions
    - `convert 6.jpg -scale x150 6_x150.jpg`
      - 6_x150
- If you want to create a copy of an image with dimensions that are a percentage of the original…
  - Create a copy that has dimensions 10% of the original
    - `convert 6.jpg -scale 10% 6_10pct.jpg`
      - 6_10pct

Comparing outputs (you can use `identify filename.jpg` to get this info):

| filename | W x H | size |
| --- | :-: | --- |
| 6.jpg | 2560x1600 | 527 KB |
| 6_200x150.jpg | 200x150 | 8 KB |
| 6_200x.jpg | 200x125 | 7 KB |
| 6_x150.jpg | 240x150 | 9 KB |
| 6_10pct.jpg | 256x160 | 10 KB |

**Comment by mfreema5** [comment]
Speaking of `6.jpg`, I did some rooting around, and the copyright on that image appears to belong to one [Eric Gevaert](https://nl.linkedin.com/pub/eric-gevaert/a/b96/305). (It's in his portfolios here: [www.dreamstime.com](http://www.dreamstime.com/royalty-free-stock-image-mountain-biker-beach-su-image2401026) and here: [shutterstock](http://www.shutterstock.com/pic-3216200/stock-photo-silhouette-of-a-mountain-biker-on-beach-and-sunset.html?src=iyC9E_2lkG3VBdT3imbsZA-1-2).)  Yeah, I know&mdash;it's all over the place in the intarwebs.  But I'm unsure whether or not a copyright lapses simply because it's not being exercised.

**Comment by mfreema5** [comment]
I don't know exactly what you were going for with `6.jpg`, but here are a few pics that might work as a replacement.  I grabbed them off of Flickr, and all are available under some flavour of [Creative Commons license](http://creativecommons.org/licenses/).

5809096765_06d4b295dd_m [link](https://www.flickr.com/photos/strelban/5809096765)

14966039193_a207904e15_m [link](https://www.flickr.com/photos/misland/14966039193)

15237688046_eb7b1637bc_m [link](https://www.flickr.com/photos/drriss/15237688046)

7959472360_91fba3ceec_m [link](https://www.flickr.com/photos/zedzap/7959472360)

4627860464_1e63d7e1ec_m [link](https://www.flickr.com/photos/paldies/4627860464)

160765772_552313a4b9_m [link](https://www.flickr.com/photos/gkamin/160765772)

**Comment by mfreema5** [comment]
New year.  New semester.  Closing old Pulls.

**Pull request closed without merging**
